"""
Task and Device dataclasses for the MARL edge offloading environment.
Based on the system model in ExplabOff (Ren et al., INFOCOM 2025).
"""
from dataclasses import dataclass, field
from typing import Optional, List


@dataclass
class Task:
    """A computation task generated by a mobile device."""
    task_id: int
    data_size: float          # bits
    cpu_cycles_per_bit: float # cycles per bit
    max_latency: float        # seconds
    arrival_time: int = 0     # time slot when task arrives

    # Execution tracking
    offload_ratio: float = 0.0          # ρ ∈ [0,1]
    target_es: Optional[int] = None     # None = local execution
    completed: bool = False
    completion_time: Optional[int] = None
    latency: float = 0.0
    energy_consumed: float = 0.0
    deadline_met: bool = False

    @property
    def total_cpu_cycles(self) -> float:
        """Total CPU cycles needed for this task."""
        return self.data_size * self.cpu_cycles_per_bit

    def is_expired(self, current_time: int) -> bool:
        return (current_time - self.arrival_time) > self.max_latency

    def reset(self):
        self.offload_ratio = 0.0
        self.target_es = None
        self.completed = False
        self.completion_time = None
        self.latency = 0.0
        self.energy_consumed = 0.0
        self.deadline_met = False


@dataclass
class Device:
    """A mobile device (MD) or edge server (ES)."""
    device_id: int
    device_type: str         # 'mobile' or 'edge'
    cpu_capacity: float      # cycles per second
    energy_budget: float     # Joules (for mobile devices)
    location: tuple = (0.0, 0.0)

    # Runtime state
    current_energy: float = 0.0
    tasks_queue: List[Task] = field(default_factory=list)

    def __post_init__(self):
        self.current_energy = self.energy_budget

    @property
    def queue_load(self) -> float:
        """Total CPU cycles in the queue."""
        return sum(t.total_cpu_cycles * (1 - t.offload_ratio) 
                   if self.device_type == 'mobile'
                   else t.total_cpu_cycles * t.offload_ratio
                   for t in self.tasks_queue if not t.completed)

    @property
    def available_capacity(self) -> float:
        return self.cpu_capacity

    def reset(self):
        self.current_energy = self.energy_budget
        self.tasks_queue.clear()
